title: "Amanda (Ruirui) Zhang"
email: rr_application@163.com
description: >- # this means to ignore newlines until "baseurl:"
  I hope to place myself in the gap between technology and humanity to augment humanity with technology and pay close attention to people's welfare.
baseurl: "/" 
url: "https://ruiruizhang.github.io/" 
twitter_username: ruirui-zhang
github_username:  ruirui-zhang

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
